# InnerOS Automation Daemon Configuration

daemon:
  check_interval: 60
  log_level: INFO

# File watching configuration
file_watching:
  enabled: true  # Enable to watch YouTube notes
  watch_path: ./knowledge/Inbox
  debounce_seconds: 2.0
  ignore_patterns:
    - "*.tmp"
    - ".git/*"
    - ".obsidian/*"

# Screenshot handler
screenshot_handler:
  enabled: false  # Disable for initial test
  onedrive_path: ~/OneDrive/Screenshots
  knowledge_path: ./knowledge/Media/Pasted Images
  ocr_enabled: false

# Smart link handler  
smart_link_handler:
  enabled: false  # Disable for initial test
  vault_path: ./knowledge
  similarity_threshold: 0.75
  max_suggestions: 5

# YouTube handler (TDD Iteration 9 + Rate Limit Mitigation)
youtube_handler:
  enabled: true
  vault_path: ./knowledge
  max_quotes: 7
  min_quality: 0.7
  processing_timeout: 300
  # Rate limit mitigation with exponential backoff (TDD Iteration 1)
  rate_limit:
    max_retries: 3           # Maximum retry attempts (0-10)
    base_delay: 5            # Initial delay in seconds (1-30)
    max_delay: 60            # Maximum delay cap in seconds (10-300)
    backoff_multiplier: 2    # Exponential multiplier (1.5-5)
