# InnerOS Metadata Validation Configuration

# Valid note types
valid_types:
  - permanent
  - fleeting
  - literature
  - MOC

# Valid note statuses
valid_statuses:
  - inbox
  - promoted
  - draft
  - published

# Valid visibility options
valid_visibilities:
  - private
  - shared
  - team

# Required fields for all note types
required_fields:
  - type
  - created
  - status

# Type-specific required fields
type_specific_fields:
  permanent:
    - tags
  fleeting:
    - tags
  literature:
    - tags
  MOC:
    - tags

# Date format validation
date_formats:
  - "%Y-%m-%d %H:%M"  # YYYY-MM-DD HH:MM
  - "%Y-%m-%d"        # YYYY-MM-DD
