name: CI - Quality Gates

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint-and-test:
    name: Lint & Test (macOS)
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          
      - name: Create virtual environment
        run: |
          python3 -m venv development/venv
          
      - name: Install dependencies
        run: |
          source development/venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black pyright pytest pytest-cov
          
      - name: Run linters (ruff)
        run: |
          source development/venv/bin/activate
          make lint
          
      - name: Run type checker (pyright)
        run: |
          source development/venv/bin/activate
          make type
        continue-on-error: true  # pyright optional for now
          
      - name: Run unit tests
        run: |
          source development/venv/bin/activate
          make unit
        env:
          PYTHONPATH: development
          
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7
          
  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    if: always()
    
    steps:
      - name: Check results
        run: |
          if [ "${{ needs.lint-and-test.result }}" == "failure" ]; then
            echo "❌ CI checks failed"
            exit 1
          else
            echo "✅ CI checks passed"
          fi
